# theme = "dark_plus"
# theme = "mytheme"
theme = "brighty"
# theme = "simple"
# theme = "jk1"
# theme = "blackwhite"
# theme = "cyan_light"
# theme = "dracula"

[editor]
soft-wrap.enable = true
line-number = "relative"
mouse = false
bufferline = "always"
auto-format = false
true-color = true
auto-info = true
color-modes = true
# cursorline = true

[editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace]
render = "all"

[editor.file-picker]
hidden = false

[keys.normal.g]
o = "jump_backward"
O = "jump_forward"

# [editor.lsp]
# display-inlay-hints = true
